### ISSUE TITLE
QEMU removed "--disable-sanitizers" option?

### ISSUE THREAD

**Issue by Chan9Yan9** [HexHive/ViDeZZo#14]
Hi, I have found that in the current **master** branch, QEMU's configure no longer has the --disable-sanitizers option, while it is still present in the **stable-9.1.0** version. 
This will cause the command `make qemu qemu-coverage` in step 2 fail to compile qemu.
I am currently trying to confirm the specific commit version where this change was made.

**Comment by cyruscyliu** [comment]
Hey did you address this issue? Sorry, I forgot this totally.

**Comment by Chan9Yan9** [comment]
Sure! Here's the translation of the sentence into English:

"Well, I found a commit on GitLab where it seems that QEMU has split `--enable-sanitizers` into `--enable-asan` and `--enable-ubsan`. The specific commit ID is [`cb771ac1`"](https://gitlab.com/qemu-project/qemu/-/commit/cb771ac1f59ced0aba5acedacfd4e92a9d0727b6).

**Comment by Chan9Yan9** [comment]
Well, I only modified the QEMU configure sanitizer options in a few scripts within the videzzo_qemu folder. I have verified that they can compile QEMU properly, but I'm not sure if this will introduce other issues. Here is my patch: [d097238](https://github.com/HexHive/ViDeZZo/commit/d097238a130bd063350a7d9471f0c83f2fa12fc2)

**Comment by cyruscyliu** [comment]
Thank you!

**Comment by blabla-my** [comment]
I also encountered this problem. 

After debugging and searching, I found it is because videzzo-llvm-project is not compatible well with ubuntu 22.04, which is the base image of ViDeZZo container. I need to modifiy videzzo-llvm-project to mitgate the problem. 

Here is the detailed root cause and solution: https://github.com/cyruscyliu/videzzo-llvm-project/pull/1
